name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["dev", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: frizinak/metrics@latest
        with:
          user: frizinak
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Brussels

          base: header, repositories, metadata

          plugin_achievements: yes
          plugin_achievements_threshold: B

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_threshold: 1%

          plugin_lines: yes

          plugin_followup: yes
          plugin_followup_sections: user
